name: Deploy OpenAI API Worker

on:
  push:
    branches: [ main ]
    paths:
      - 'apps/api/openai-api-worker/**'
      - '.github/workflows/deploy-openai-api-worker.yml'
      - 'package.json'
      - 'package-lock.json'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    concurrency:
      group: openai-api-worker-${{ github.ref }}
      cancel-in-progress: true

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Build & Deploy to Cloudflare Workers
        uses: cloudflare/wrangler-action@v3
        with:
          wranglerVersion: "4.16.1"
          workingDirectory: "apps/api/openai-api-worker"
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          environment: production
          secrets: |
            OPENAI_API_KEY
          command: deploy --minify
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}